# Generated by Django 4.0.2 on 2022-03-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petstagramuser',
            name='has_profile',
            field=models.BooleanField(default=None),
        ),
    ]
