# Generated by Django 4.0.2 on 2022-03-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_petstagramuser_has_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petstagramuser',
            name='has_profile',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
