# Generated by Django 4.0.2 on 2022-02-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_petphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petphoto',
            old_name='publised',
            new_name='published',
        ),
    ]
