# Generated by Django 4.0.2 on 2022-02-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_publised_petphoto_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='petphoto',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
