# Generated by Django 4.0.2 on 2022-02-04 13:05

from django.db import migrations, models
import petstagram.main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_petphoto_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='images', validators=[petstagram.main_app.validators.validate_image_size_5]),
        ),
    ]
